version: '3.7'

services:
  service1:
    build:
      context: ./
    image: "mycloudstorage:1.0"
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      spring_datasource_url: jdbc:postgresql://127.0.0.1:5433/postgres
      spring_datasource_username: postgres
      spring_datasource_password: postgres
      spring_liquibase_enabled: true
      spring_liquibase_change-log: classpath:db/changelog/db.changelog-master.yaml
      jwt_secret_access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      jwt_secret_refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

  database:
    image: postgres
    ports:
      - "5433:5432"
      #volumes:
      #- ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  Liquibase:
    # Image to be pulled from Docker Hub
    image: liquibase/liquibase:latest #4.9.1
    # Name of the container
    container_name: Liquibase_container
    # Setting depends_on to PostgreSQL container to wait till the service is ready to accept connections
    depends_on:
      - database
    # Volume to add the liquibase collection of scripts
    volumes:
      - ./src/main/resources/db/changeLog/:/liquibase/changelog/
    # Command to run the liquibase update service
    command: --defaults-file=/liquibase/changelog/liquibase.properties update