version: '3.7'

services:
  database:
    image: postgres
    ports:
      - "5433:5432"
      #volumes:
      #- ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  liquibase:
    # Image to be pulled from Docker Hub
    image: liquibase/liquibase:4.24.0 #4.9.1
    # Name of the container
    container_name: Liquibase_container
    # Setting depends_on to PostgreSQL container to wait till the service is ready to accept connections
    depends_on:
      - database
    # Volume to add the liquibase collection of scripts
    volumes:
      - ./src/main/resources/db/changelog/:/liquibase/changelog/
    # Command to run the liquibase update service
    command: liquibase --url="jdbc:postgresql://database:5432/postgres" --changeLogFile=./changelog/db.changelog-master.yaml --username=postgres --password=postgres --defaults-file=/liquibase/changelog/liquibase.properties  update
    #command: --defaults-file=/liquibase/changelog/liquibase.properties update

  service1:
    build:
      context: .
    image: "mycloudstorage:1.0"
    ports:
      - "8081:8080"
    depends_on:
      - liquibase
    environment:
      spring_datasource_url: jdbc:postgresql://127.0.0.1:5433/postgres
      spring_datasource_username: postgres
      spring_datasource_password: postgres
      spring_liquibase_enabled: true
      spring_liquibase_url: jdbc:postgresql://database:5432/postgres
      spring_liquibase_username: postgres
      spring_liquibase_password: postgres
      spring_liquibase_change-log: classpath:db/changelog/db.changelog-master.yaml
      jwt_secret_access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
      